{
 "title": "Demo dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Pipeline Tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(started),\n  'Stage ' || stage::text as metric,\n  extract(epoch from ended-started)\nFROM\n  pipeline_stages\nWHERE\n  $__timeFilter(started)\nORDER BY started"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "rawSql": "select * from users;" }
   ]
  },
  {
   "title": "Users Created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(created, '1h', 0),\n  count(*) AS \"value\" \nFROM users\nWHERE\n  $__timeFilter(created)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}